### ISSUE TITLE
Exclamation point remains in Catacombs doorway even after opening the door

### ISSUE THREAD

**Issue by nmadadair** [TwilioQuest/twilioquest-api-academy#14]
The door is closed when the player first approaches (even after retrieving the key, etc.) and the exclamation appears to open the doors. Once they are open, when the player passes through the open doorway in either direction, the exclamation point appears again, with no interactivity.

<img width="578" alt="Screen Shot 2022-09-26 at 4 21 23 PM" src="https://user-images.githubusercontent.com/109177652/192377445-c07b6da4-d21f-4bec-aab1-6764d328ba14.png">

**Comment by MarvelProgramming** [comment]
Technically, a fix was already merged for this in the `main` branch. However, since `milestone-1-aa3` has had structural changes to the `event.js` files, a [new fix](https://github.com/TwilioQuest/twilioquest-api-academy/pull/86) was necessary.
