### ISSUE TITLE
Create Art / House Avatar Uniforms x4

### ISSUE THREAD

**Issue by nmadadair** [TwilioQuest/twilioquest-api-academy#20]
The player will get the house uniform of their chosen house upon completing the House Ceremony.

**Comment by kerrielake** [comment]
Just adding a note here that the uniforms will probably be 3 items each: Suit jacket/top, skirt, and pants. We can default to the pants if that's easier, but I think it's good to give the player the option between the pants and skirt, especially since they are both used for the students.
