### ISSUE TITLE
Implement Lovelace Spell Animation

### ISSUE THREAD

**Issue by nmadadair** [TwilioQuest/twilioquest-api-academy#22]
When the player opens the secret Lovelace Library door using the spell, the corresponding animation should play (player using wand/spell affecting world). The door should then be unlocked allowing the player to walk through.

**Comment by nmadadair** [comment]
@rmkubik Ryan will clarify the technical requirements for this.

**Comment by rmkubik** [comment]
Player animations are split into two parts. 
1. The actual player pulling out the wand animation frame
2. The running magic spell effect animation

We can see this implemented for [the flamethrower in the Forest of Open Source](https://github.com/TwilioQuest/twilioquest-open-source/blob/main/levels/open_source/events/flamethrower.js).

Callouts from the above implementation:
- This code checks the player's facing
  - We should use player.facing === 'UP'/'LEFT'/'RIGHT'/'DOWN' now.
- Creates a game sprite dynamically with the directionally appropriate flamethrow effect
- Then we trigger "useTool" to start the player animation, we'll want to useTool `"wand"` for our implementation
- After the animation is done, we clean up after ourselves by removing the animation sprite

This function can be used wherever in scripting to play a spell animation.

**Comment by rmkubik** [comment]
In working on this solution:

If there are commonalities in this implementation and the flamethrower implementation, we should propose new `world` functions that might make creating entities dynamically easier or implementing more complex tools easier.

**Comment by nmadadair** [comment]
FYI, I removed one of the custom properties on the secret library door at the very end of the Lovelace Tower map. The door should be interactable even when `!completedObjectives["api-04-remote-and-local"]` but should only be spellable when `completedObjectives["api-04-remote-and-local"]`. There is a conversation that launches if the player tries to interact with the door before completing the objective that tells them to complete it to get the spell.

**Comment by MarvelProgramming** [comment]
@rmkubik Is there a particular sprite/sprites we wanted to use for this? I know we have the sparkles appear above the door when it's interactable, but for the magic spell effect animation, what else did we want to use there?

**Comment by rmkubik** [comment]
We wanted to use these spell effects, the way we do the flamewthrower in the open source forest:
https://github.com/TwilioQuest/twilioquest-base/blob/main/tilesets/Operator_ToolEffects_UpDown.png

**Comment by nmadadair** [comment]
@MarvJohnson Playing through with some last minute testing: 

- The spellable lovelace shine marker should not be on the Lovelace door from the `lovelacehallway` to the lovelace tower map, since the player doesn't need a spell to open it. I noticed it appears when the door opening animation plays.
- door from lovelace tower to library is currently interactable (exclamation point appears) but the player cannot do anything. We should either make the door completely un-interactable until they complete obj 4, or we should make sure the exclamation point interaction brings up the `library-door` conversation (it's possible you have an outstanding PR that resolves this. If so, apologies!)

**Comment by MarvelProgramming** [comment]
> @MarvJohnson Playing through with some last minute testing:
> 
> * The spellable lovelace shine marker should not be on the Lovelace door from the `lovelacehallway` to the lovelace tower map, since the player doesn't need a spell to open it. I noticed it appears when the door opening animation plays.
> * door from lovelace tower to library is currently interactable (exclamation point appears) but the player cannot do anything. We should either make the door completely un-interactable until they complete obj 4, or we should make sure the exclamation point interaction brings up the `library-door` conversation (it's possible you have an outstanding PR that resolves this. If so, apologies!)

These should be fixed [here](https://github.com/TwilioQuest/twilioquest-api-academy/pull/94#:~:text=%2DRemoved%20unneeded%20sparkle%20object%20from%20lovelacehallway%20door) and [here](https://github.com/TwilioQuest/twilioquest-api-academy/pull/94#:~:text=%2DFixed%20bug%20where%20doors%20would%20become%20interactable%20again%20if%20the%20player%20left%20the%20their%20scene%20and%20went%20back)

**Comment by MarvelProgramming** [comment]
> In working on this solution:
> 
> If there are commonalities in this implementation and the flamethrower implementation, we should propose new `world` functions that might make creating entities dynamically easier or implementing more complex tools easier.

+1 on this. The implementations ended up being practically the sam. I'm sure there's a way we could reduce the overhead for achieving similar features moving forward!

**Comment by MarvelProgramming** [comment]
Closing this as it was covered in PR #94!
