### ISSUE TITLE
api-02-async-await / learn async await locally

### ISSUE THREAD

**Issue by nmadadair** [TwilioQuest/twilioquest-api-academy#40]
- [ ] objective.json
- [ ] description.md
- [ ] validator.js
- [ ] walkthrough.md

For more details, reference the [original objective planning doc](https://docs.google.com/document/d/1Esz69gd10vK4Btnk_pn0pmKTUgIq9f7sCrmnMVyOt5E/edit#heading=h.uoyv4k1cq39u).

## Objective online
- Some APIs need to take time to do their thing
- We can use await inside of async function to let them take as much time as they need
- Read from a directory and use async/await to select the last file in the provided directory
- This is an example of what the user's code might end up looking like
```
const fs = require('fs').promises;

async function findLastFileInDir(dirPath) {
  const rootFiles = await fs.readdir(dirPath);
  
  return rootFiles[rootFiles.length - 1];
}

// Test your function
async function test() {
  console.log(await findLastFileInDir('/'));
}

test();
```
- setting up the test harness is a little uglier when we need to use async/await since top level await is not supported in node (especially not node 12...)

**Comment by MarvelProgramming** [comment]
This is done as of #57. Closing!
