### ISSUE TITLE
api-03-fetch / fetch from twilioquest API

### ISSUE THREAD

**Issue by nmadadair** [TwilioQuest/twilioquest-api-academy#41]
- [x] objective.json
- [x] description.md
- [x] validator.js
- [x] walkthrough.md

For more details, reference the [original objective planning doc](https://docs.google.com/document/d/1Esz69gd10vK4Btnk_pn0pmKTUgIq9f7sCrmnMVyOt5E/edit#heading=h.uoyv4k1cq39u).

## Objective outline
- We saw an example of async behavior on our own computer
- Web APIs let us do async behavior on someone else's computer, a server
- In order to write a proper divination spell, we need to get information from elsewhere in the cloud
- player should write a fetch call to a JSON API we design in #53
- player should return a list of all book titles, this will require a map or loop

**Comment by MarvelProgramming** [comment]
This is done as of #58. Closing!
