### ISSUE TITLE
api-04-remote-and-local / fetch data from our API and the process it locally

### ISSUE THREAD

**Issue by nmadadair** [TwilioQuest/twilioquest-api-academy#42]
- [x] objective.json
- [x] description.md
- [x] validator.js
- [x] walkthrough.md

For more details, reference the [original objective planning doc](https://docs.google.com/document/d/1Esz69gd10vK4Btnk_pn0pmKTUgIq9f7sCrmnMVyOt5E/edit#heading=h.uoyv4k1cq39u).

## Objective outline
- Get all author names who have written a document longer than X pages where X is an argument passed into the function
- depends on #53

**Comment by MarvelProgramming** [comment]
This is done as of #59. Closing!
