### ISSUE TITLE
api-05-get-patch / get an author's contact URL and post them a book review

### ISSUE THREAD

**Issue by nmadadair** [TwilioQuest/twilioquest-api-academy#43]
- [x] objective.json
- [x] description.md
- [x] validator.js
- [x] walkthrough.md

For more details, reference the [original objective planning doc](https://docs.google.com/document/d/1Esz69gd10vK4Btnk_pn0pmKTUgIq9f7sCrmnMVyOt5E/edit#heading=h.uoyv4k1cq39u).

## Objective outline
- Use divination URL from before to fetch an author
- Find the author's contact URL
- Post them a review of their book/document/article? 
  - Is there some actual type of text we want to collect from players here that would be useful?

**Comment by MarvelProgramming** [comment]
When testing this, is the plan to check for an entry belonging to the user -- sort of like what we do for the [open-pixel-art](https://github.com/twilio-labs/open-pixel-art) objective(s)?

**Comment by MarvelProgramming** [comment]
This is done as of #60. Closing!
