### ISSUE TITLE
Implement Secret Library Doors Triggers

### ISSUE THREAD

**Issue by nmadadair** [TwilioQuest/twilioquest-api-academy#48]
- When the player enters secret Lovelace Library, the exit door (that leads back to Lovelace Tower) is locked.
- Once they complete the Obj (`obj5Complete === true`) and reveal Fredric's message, the Exit door from the Library becomes spellable, with the blue sparkle marker animation appearing on the door.

**Comment by MarvelProgramming** [comment]
This may be somewhat challenging due to the player spawning (when they start/restart the game) as well as being able to teleport directly back to the FogOwl. We can chat more about this, though!

**Comment by nmadadair** [comment]
This is a great point. It's not critical and may not be the best way to move forward, so I'll keep thinking about it in the meantime. Thanks for flagging this though!

**Comment by nmadadair** [comment]
This should be done, but need to test.

**Comment by nmadadair** [comment]
@MarvJohnson Quick follow up since I know you are working on the various door and levelChange triggers: 

- let's simplify this so that the player at any time can exit the library and go back to lovelace tower.
- instead, the other door that leads back to the corridor should stay locked with no sparkle animation until the player has completed the 5th objective.

**Comment by rmkubik** [comment]
This work has changed and issue is not necessary any longer.
