### ISSUE TITLE
TwilioQuest Server endpoint for querying in divination spell

### ISSUE THREAD

**Issue by rmkubik** [TwilioQuest/twilioquest-api-academy#53]
We decided to have this to return a catalogue of documents and their authors. This should have static information Nicole designs. We can include books from the Librarian and other locations in The Cloud.

The requirements of this API need to be designed alongside api-03, 04, and 05.

**Comment by rmkubik** [comment]
Perhaps a URL:
https://twilio.com/quest/magic/divination/books

Then we could have /magic be a root for future spells we want to have the player "create"?

**Comment by MarvelProgramming** [comment]
@rmkubik How do we feel about adding something like `game/` to the route (e.g. https://twilio.com/quest/game/magic/divination/books)? My thinking here is that `game/` would create a distinction between game-specific endpoints and ones belonging exclusively to the site (i.e. `game/` would act as the root for any endpoints consumed in-game)

**Comment by nmadadair** [comment]
I'm planning on have four book authors and blurbs drafted by the end of the week. If we need more we have the four from TOIK.

**Comment by nmadadair** [comment]
[Google Spreadsheet](https://docs.google.com/spreadsheets/d/1emBrtskRWPFhLGlo289Q6vxYCoei6LZ_sxKs20ylYB8/edit#gid=0) with author names and other data points. @rmkubik @MarvJohnson Do we need more than four? Do we need additional data here?

**Comment by rmkubik** [comment]
03 - GET /quest/magic/divination
      - 200 OK - ALAKAZAM
      - validation is just check if the function returns the keyword

04 - GET /quest/magic/divination/books
      - 200 OK - returns a JSON blob
      - validation - needs author names, page count 
 
 05 - GET /quest/magic/divination/books
       - fetch the books
       - an author has a "contact url" listed in the JSON blob
       - Post a JSON payload to the contact URL
          - id - pass in a guid to the function
          - review text
 
/quest/magic/divination - respond to GET request 200 OK and respond with "MAGIC WORD"
/quest/magic/divination/books - respond to GET with 200 OK and return book JSON blob
/quest/magic/divination/reviews - respond to POST with 201 CREATED
/quest/magic/divination/reviews/:id - respond to GET with 200 OK and review JSON

book JSON:
```
{
  id: 123123
  review: "/reviews/123123/"
  author: {
     name: "bob builder",
  },
  metadata: {
     pageCount: 123
  }
}
```

review body: 
```
{
   id: 123123123,
  data: "asdf asdf asd f"
}
```

**Comment by MarvelProgramming** [comment]
> [Google Spreadsheet](https://docs.google.com/spreadsheets/d/1emBrtskRWPFhLGlo289Q6vxYCoei6LZ_sxKs20ylYB8/edit#gid=0) with author names and other data points. @rmkubik @MarvJohnson Do we need more than four? Do we need additional data here?

I don't know that we'll need more than 4. We've updated objective 5 from being focussed on reviews to "repairing a damaged book". I believe the idea was to make a "GET" request to fetch the data needed to fix a book, then to "POST" that data to the book in question. When it comes to additional data, perhaps we could iron that out during our meeting today?

**Comment by rmkubik** [comment]
Update after milestone sync:

03 - GET /quest/magic
- returns a "magic phrase" that activates the operator's magic

04 - GET /quest/magic/divination
- returns a JSON blob with an array of books

```js
{
 data: [
   {
       // book data goes here   
   },
   . . .
 ]
}
```

book
```js
{
  id: 123123
  author: {
     name: "bob builder",
  },
  metadata: {
     pageCount: 123
  }
}
```

05 - GET /quest/magic/divination?target=lovelace_secret_statue
```js
{
  name: "lovelace secret statue",
  key: "lovelace_secret_statue",
  operational: false,
  inscription: "kjlahsdflkXXHAHD@&&(*#(@*(!adsfadf" // poem with sections cut out
}
```
- returns a JSON blob with information about the statue
- PATCH /quest/magic/divination?target=lovelace_secret_statue
```js
{
  id: player-guid
  data: {
    inscription: "string with the repaired inscription" // entire poem written correctly
  }
}
```

**Comment by MarvelProgramming** [comment]
I think the only thing I'm blocked on with regards to this, is how we want to handle players "repairing" inscriptions. Currently they make a get request to `/quest/magic/divination?target=lovelace_secret_statue` and get back an object that includes the broken inscription. We assume the patch they make has the repaired inscription, but how are players doing that locally? Any ideas @rmkubik @nmadadair?

**Comment by rmkubik** [comment]
We should have them interact with a book or something else in the library room. The book should show the correct inscription and they can use that to repair the corrupted one.

We should only use part of the inscription in the earlier replaceAll objective so that the player needs to find the book in the hidden library to do the repiar.

**Comment by rmkubik** [comment]
So the `PATCH` to `/quest/magic/divination?target=lovelace_secret_statue` should:

- [x] validate that there is a unique player guid present
- [x] validate the inscription is correct against the model

and only write to the DB if those things are correct.

Otherwise, we should return useful error messages so the TQ validator can give the player feedback.

**Comment by MarvelProgramming** [comment]
This is all done as of [this PR merger](https://github.com/twilio/twilioquest-server/pull/1818)! Gonna go ahead and close this
