### ISSUE TITLE
Implement Fredric Threatening Message Trigger / Secret Lovelace Library

### ISSUE THREAD

**Issue by nmadadair** [TwilioQuest/twilioquest-api-academy#66]
Upon hacking the final mission objective in the secret Lovelace Library (`if obj5Complete === true`) and closing the hacking interface, Fredric's image and dialogue should appear containing his threatening message.

**Comment by MarvelProgramming** [comment]
Would you mind linking to (or pasting) the text for Fredric's threatening message here?

**Comment by nmadadair** [comment]
the conversation file is fredric-threat-lovelace.pug under levels > lovelace_tower > conversations. [Draft doc](https://docs.google.com/document/d/1Qtbe9A7JKVXCKXvBPTcWoN8FWvcF5aaSE63KlvRaia4/edit#heading=h.a8d7hn9v96iy)

**Comment by nmadadair** [comment]
This should be done/ testing needed still.
