### ISSUE TITLE
Implement Lovelace Sparkle Animation / Lovelace Tower

### ISSUE THREAD

**Issue by nmadadair** [TwilioQuest/twilioquest-api-academy#69]
- [x] `If obj4Complete === false`, the sparkle animation is hidden and the Lovelace Library door is not interactable. 
- [x] `If obj4Complete === true`, the sparkle animation appears and the Lovelace Library door becomes interactable and spellable.

**Comment by MarvelProgramming** [comment]
Is "obj4" referring to the [api-04-remote-and-local objective](https://github.com/TwilioQuest/twilioquest-api-academy/issues/42)?

**Comment by nmadadair** [comment]
@MarvJohnson Yep

**Comment by MarvelProgramming** [comment]
@rmkubik This was taken care of in the [map PR that was merged](https://github.com/TwilioQuest/twilioquest-api-academy/pull/76), in case we wanted to close it. I think I forgot to mention it in the commit, but I went ahead and updated the comment for the PR

**Comment by rmkubik** [comment]
Great! Closing!
