### ISSUE TITLE
Animate Lovelace doors opening / Various Maps

### ISSUE THREAD

**Issue by nmadadair** [TwilioQuest/twilioquest-api-academy#71]
- [x] Courtyard: When the player approaches the main doors, they should swing open and trigger levelChange to main hall map.
- [x] Lovelace Corridor: When the player approaches the blue door in the Lovelace corridor, the door should automatically open and trigger the levelChange. 
- [x] Lovelace Tower: When the player performs the spell on the blue door at the end of Lovelace Tower, after the spell animation plays, the door should open and trigger the levelChange to the secret library.
- [x] Secret Lovelace Library: When the player performs the spell on the blue exit door inside Lovelace Library, after the spell animation plays, the door should open and trigger the levelChange back to the Lovelace corridor.
- [x] Lovelace Corridor: When the player approaches the two wooden doors in the Lovelace corridor, `if houseLovelaceComplete === true`, the doors should open and trigger levelChange to library.

**Comment by MarvelProgramming** [comment]
> When the player approaches the two wooden doors in the Lovelace corridor

Is this referring to these two doors? If so, is the plan to have the player spawn in front of the one on the left even if they went in through the right? Should be fine either way, but just thought I'd ask haha


<img width="736" alt="lovelace-corridor-example" src="https://user-images.githubusercontent.com/51891409/203449321-020b7cfc-fab1-4825-92ed-d293e34ed6be.png">

**Comment by nmadadair** [comment]
@MarvJohnson Let's have the player spawn in front of the left door. I will update the map so that the right door is not interactable and maybe has some chairs blocking it so that it's clear that door doesn't lead anywhere.

**Comment by MarvelProgramming** [comment]
@nmadadair Sounds like a plan! We'll want to wait until [this](https://github.com/TwilioQuest/twilioquest-api-academy/pull/76) PR is merged before making any changes, though

**Comment by nmadadair** [comment]
@MarvJohnson Just wondering if this PR is still unmerged? I'm noticing that most doors (main hall entrance door, Lovelace Tower door from the lovelace_hallway) are not animating open when the player enters them. Instead the two spellable doors (from Lovelace Tower to the library and from the library back to the corridor) are opening immediately before the player approaches them. 

All doors should behave the same way when it comes to the doors being animated to open (like regular doors in the Academy elsewhere). In addition, the two spellable doors should trigger the player animation to play before the animation occurs.

Please let me know if you've scripted these interactions but just haven't merged them yet. I wanted to capture what I'm seeing in any case!

**Comment by MarvelProgramming** [comment]
> @MarvJohnson Just wondering if this PR is still unmerged? I'm noticing that most doors (main hall entrance door, Lovelace Tower door from the lovelace_hallway) are not animating open when the player enters them. Instead the two spellable doors (from Lovelace Tower to the library and from the library back to the corridor) are opening immediately before the player approaches them.
> 
> All doors should behave the same way when it comes to the doors being animated to open (like regular doors in the Academy elsewhere). In addition, the two spellable doors should trigger the player animation to play before the animation occurs.
> 
> Please let me know if you've scripted these interactions but just haven't merged them yet. I wanted to capture what I'm seeing in any case!

This is pretty close to being finished. There's a bug with the `smoothTransitionBetweenOpeningAndClosing` option for doors, leading to some really awkward snapping in the animation. I've linked this issue to the [PR](https://github.com/TwilioQuest/twilioquest-api-academy/pull/79) I've been doing the work in, if you'd like to take a look at that as well!

**Comment by nmadadair** [comment]
Ok, I thought this was the case, but just wanted to check!

**Comment by MarvelProgramming** [comment]
This issue was wrapped up in #79. Gonna go ahead and close this!
