### ISSUE TITLE
Update Maps with new art assets

### ISSUE THREAD

**Issue by kerrielake** [TwilioQuest/twilioquest-api-academy#75]
- Change wooden sign to new academy sign in courtyard.json
- Add new center platforms underneath objective statues in the lovelace tower (whichever of the two colours looks better)
- Add new lounge assets to lovelace tower (blue couches, blue recoloured chairs and coffee table)

**Comment by nmadadair** [comment]
@kerrielake I made an attempt at adding the platform underneath the objective statues, but except for the final one in the library map, the first four come out a bit strange. Feel free to take a look and update if you have a better solution to mine!

**Comment by nmadadair** [comment]
API sign 
- [x] Add pug file for academy sign with school name (courtyard map)
- [x] Add sign portrait to conversations folder
- [x] Add custom properties to sign in Tiled

Lovelace Statue
- [x] Add pug file for Lovelace statue (hallway map)
